---
title: "SCENIC result"
output: html_notebook
---

# part 5

## SCENIC visualization

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/home/zju/tianfeng/single_cell_atlas")
.libPaths("/home/zju/R/x86_64-pc-linux-gnu-library/4.0")
```

```{r, include=FALSE}
source("./utils/tianfengRwrappers.R")
```

```{r fig.width=3, fig.height=3}
identifier <- "ctrl_filtered"
result_path <- paste0("./data_tables/SCENIC/",identifier)

regulonActivity <- read.csv(paste0(result_path, "/regulonActivity.csv"),row.names = 1)
topTFs <- read.csv(paste0(result_path,"/topRegulators.csv"),row.names = 1,stringsAsFactors = T)

topTFs<-na.omit(topTFs)
regulonActivity <- regulonActivity[,levels(topTFs$seuratCluster)] #调换列顺序

top5 <- topTFs %>% group_by(seuratCluster) %>% slice_max(n = 8, order_by = RelativeActivity)

#根据已知的top5更新行顺序
top_regulonActivity <- regulonActivity[sapply(top5$Regulon, function(e) {which(rownames(regulonActivity) == e)}), ]


# annotation_row <-  data.frame(cluster = factor(top5$seuratCluster), row.names = make.names(top5$Regulon,TRUE)) #make.names用来生成不冲突的行

# 去掉extended和重复的行
row_index <- intersect(rownames(top_regulonActivity) %>% grep(".", ., fixed=TRUE, invert=TRUE), rownames(top_regulonActivity) %>% grep("extended", ., invert=TRUE))
top_regulonActivity <- top_regulonActivity[row_index, ]

annotation_row <- rownames(top_regulonActivity) %>% sapply(., function(x) strsplit(x, ' (', fixed = T)[[1]][1])

TFs_heatmap <- pheatmap(top_regulonActivity, breaks = unique(c(seq(-2,2, length=400))), color = colorRampPalette(c("#1E90FF", "white", "#ff2121"))(400), border_color = NA, cluster_rows = FALSE, cluster_cols = FALSE, labels_row = annotation_row, main = "regulonActivity",angle_col = 0, show_rownames = T)
ggsave(paste0("./figures/SCENIC_result/",identifier,"_TFs_activity.tiff"), device = tiff, width = 5,height = 5,plot = TFs_heatmap)

print(TFs_heatmap)
```

```{r}
heatmapTFs <- topTFs %>% group_by(seuratCluster) %>% slice_max(n = 500, order_by = RelativeActivity)

top_regulonActivity <- regulonActivity[sapply(heatmapTFs$Regulon, function(e) {which(rownames(regulonActivity) == e)}), ]
# annotation_row <-  data.frame(cluster = factor(top5$seuratCluster), row.names = make.names(top5$Regulon,TRUE))
genes_to_show <- c(as.character(top5$Regulon), "PRDM6_extended (53g)","PRDM6 (51g)")


##获得基因和细胞聚类信息
cluster_info <- colnames(regulonActivity)

##筛选矩阵为要画热图的基因
mat <- top_regulonActivity

#获得要展示的基因在热图中的位置信息
gene_pos <- match(genes_to_show, rownames(mat))
row_anno <- rowAnnotation(gene=anno_mark(at=gene_pos,labels = genes_to_show))

col <- colors_list
names(col) <- cluster_info
top_anno <- HeatmapAnnotation(cluster=anno_block(gp=gpar(fill=col),labels = cluster_info,
                                                 labels_gp = gpar(cex=1,col='black'))) ## 顶端的cluster注释
col_fun <-  colorRamp2(c(-2, 0, 2), c("#1E90FF", "white", "#ff2121")) #颜色

svg("./figures/SCENIC_result/HSDTFs.svg",height = 6,width = 10)
Heatmap(mat, cluster_rows = FALSE, cluster_columns = FALSE, 
        show_column_names = FALSE, show_row_names = FALSE,
        column_split = cluster_info, top_annotation = top_anno,  
        column_title = NULL, right_annotation = row_anno, 
        heatmap_legend_param = list(
          title='Regulon Activity', title_position='leftcenter-rot'), col = col_fun)
dev.off()
```

```{r}
top_regulonActivity[heatmapTFs$Regulon,]
heatmapTFs$Regulon
top_regulonActivity
subset(top_regulonActivity)
```

## compare TFs activity between HSD and ctrl

### overlap TFs

```{r fig.width=3, fig.height=3}
ctrlTFs <- read.csv("./data_tables/regulonActivity_ctrl.csv",row.names = 1)
HSDTFs <- read.csv("./data_tables/regulonActivity_HSD.csv",row.names = 1)

# 只保留转录因子名称
ctrlTF_name <- lapply(rownames(ctrlTFs), function(x) strsplit(x," (", fixed = T)[[1]][1]) %>% as.character()
HSDTF_name <- lapply(rownames(HSDTFs), function(x) strsplit(x," (", fixed = T)[[1]][1]) %>% as.character()

rownames(ctrlTFs) <- ctrlTF_name
rownames(HSDTFs) <- HSDTF_name

common_TFname <- intersect(ctrlTF_name, HSDTF_name)
diff_TFs <- HSDTFs[common_TFname,] - ctrlTFs[common_TFname,]

# write.csv(diff_TFs,"./data_tables/diff_TFs.csv")
diff_TFs <- diff_TFs[rownames(diff_TFs) %>% grep("extended", ., fixed = TRUE, invert = TRUE), ]
diff_heatmap <- pheatmap(diff_TFs, breaks = unique(c(seq(-2,2, length=400))), 
                 color = colorRampPalette(c("#1E90FF", "white", "#ff2121"))(400),
                border_color = NA, cluster_rows = TRUE, cluster_cols = FALSE,
                main = "HSD - ctrl",angle_col = 0, show_rownames = T)
ggsave("./figures/SCENIC_result/HSDvsCtrl_TFs_activity.tiff", device = tiff, width = 5,height = 5, plot = diff_heatmap)

pheatmap(ctrlTFs[dd[["tree_row"]][["labels"]][dd[["tree_row"]][["order"]]],],breaks = unique(c(seq(-2,2, length=400))), 
                 color = colorRampPalette(c("#1E90FF", "white", "#ff2121"))(400),
                border_color = NA, cluster_rows = FALSE, cluster_cols = FALSE,
                main = "ctrl",angle_col = 0, show_rownames = T)

pheatmap(HSDTFs[dd[["tree_row"]][["labels"]][dd[["tree_row"]][["order"]]],],breaks = unique(c(seq(-2,2, length=400))), 
                 color = colorRampPalette(c("#1E90FF", "white", "#ff2121"))(400),
                border_color = NA, cluster_rows = FALSE, cluster_cols = FALSE,
                main = "HSD",angle_col = 0, show_rownames = T)

```

### Diff TFs

```{r fig.height=4}
pheatmap(ctrlTFs[setdiff(ctrlTF_name, HSDTF_name),], breaks = unique(c(seq(-2,2, length=400))), 
                 color = colorRampPalette(c("#1E90FF", "white", "#ff2121"))(400),
                border_color = NA, cluster_rows = F, cluster_cols = FALSE,
                main = "ctrlTFs only",angle_col = 45, show_rownames = T)



pheatmap(HSDTFs[setdiff(HSDTF_name,ctrlTF_name),], breaks = unique(c(seq(-2,2, length=400))), 
                 color = colorRampPalette(c("#1E90FF", "white", "#ff2121"))(400),
                border_color = NA, cluster_rows = F, cluster_cols = FALSE,
                main = "HSDTFs only",angle_col = 45, show_rownames = T)
```

------------------------------------------------------------------------

# show enriched motifs and TFs

```{r}
motifEnrichmentTable_wGenes_wLogo <- RcisTarget::addLogo(`2.4_motifEnrichment_selfMotifs_wGenes`)
DT::datatable(motifEnrichmentTable_wGenes_wLogo) %>% DT::saveWidget(., "./SCENIC/ctrl_filtered/motif_enrichment.html")

```

```{r fig.width=6, fig.height=6}
library(igraph)
library(stringr)
# get shared target genes
motif_enrichment_result <- read.table("./SCENIC/ctrl_filtered/output/Step2_MotifEnrichment.tsv", sep = '\t', header = 1)
regulons_asGeneSet <- readRDS("./SCENIC/ctrl_filtered/int/2.6_regulons_asGeneSet.Rds")

regulons_asGeneSet <- regulons_asGeneSet[!(names(regulons_asGeneSet) %>% str_detect(., "_extended$"))] # remove TFs with extended
# df1 <- combn(regulons_asGeneSet, 2, FUN = function(x){length(intersect(x[[1]], x[[2]]))}, simplify=T) 
df2 <- data.frame(combn(names(regulons_asGeneSet), 2, FUN = NULL, simplify=T)) 
# colnames()
df2[3,] <- combn(regulons_asGeneSet, 2, FUN = function(x){length(intersect(x[[1]], x[[2]]))}, simplify=T) %>% as.numeric()
df2 <- t(df2) %>% as.data.frame()
colnames(df2) <- c("TF1", "TF2", "weight")
df2$weight <- df2$weight %>% as.numeric()


# df3 <- data.frame(combn(names(rev(regulons_asGeneSet)), 2, FUN = NULL, simplify=T)) 
# # colnames()
# df3[3,] <- combn(rev(regulons_asGeneSet), 2, FUN = function(x){length(intersect(x[[1]], x[[2]]))}, simplify=T) %>% as.numeric()
# df3 <- t(df3) %>% as.data.frame()
# colnames(df3) <- c("TF1", "TF2", "weight")
# df3$weight <- df3$weight %>% as.numeric()

# df4 <- rbind(df2, df3)

# df4$weight[df4$weight<0.4] <- 0
# construct igraph object from adject table
TFs_regulon_network <- graph.data.frame(df2, directed=FALSE)
# is_weighted(TFs_regulon_network)

color_mapping <- c(colors_list[1:9],"lightgrey")
names(color_mapping) <- c(ctrl_filtered$celltype %>% levels(), "NA")

temp_func1 <- function(x){
  # return a color based on seurat cluster
  temp_df <- topTFs %>% filter(str_detect(Regulon, paste0("^",x)))
  if(nrow(temp_df) == 0){
    return("NA")
  }else{
    temp_df %<>% filter(RelativeActivity == max(RelativeActivity))
  return(color_mapping[temp_df$seuratCluster[[1]] %>% as.character()][[1]])}}

TFs_cluster <- sapply(names(regulons_asGeneSet), temp_func1)

# plot.igraph(TFs_regulon_network, layout=layout_with_graphopt(TFs_regulon_network, charge=0.003), edge.curved=0.4, margin=c(0,0,0,0), edge.arrow.mode=0, vertex.size=10, edge.arrow.size=0, arrow.width=0, edge.width=E(TFs_regulon_network)$weight/100, vertex.color=TFs_cluster, vertex.label.color='black')
# use edge.arrow.size (not arrow.size) to set edge's arrow attribute
```

```{r fig.width=6, fig.height=6}
df2 <- data.frame(combn(names(regulons_asGeneSet), 2, FUN = NULL, simplify=T)) 
df2[3,] <- combn(regulons_asGeneSet, 2, FUN = function(x){
  length(intersect(x[[1]], x[[2]]))/length(x[[1]])
  }, simplify=T) %>% as.numeric()
df2 <- t(df2) %>% as.data.frame()
colnames(df2) <- c("TF1", "TF2", "weight")
df2$weight <- df2$weight %>% as.numeric()


df3 <- data.frame(combn(names(rev(regulons_asGeneSet)), 2, FUN = NULL, simplify=T))
df3[3,] <- combn(rev(regulons_asGeneSet), 2, FUN = function(x){
  length(intersect(x[[1]], x[[2]]))/length(x[[1]])
  }, simplify=T) %>% as.numeric()
df3 <- t(df3) %>% as.data.frame()
colnames(df3) <- c("TF1", "TF2", "weight")
df3$weight <- df3$weight %>% as.numeric()

df4 <- rbind(df2, df3)
# df4$weight[df4$weight<0.2] <- 0

TFs_regulon_network <- graph.data.frame(df4, directed=TRUE)

# plot.igraph(TFs_regulon_network, layout=layout_with_graphopt(TFs_regulon_network, charge=0.002, niter=2000), edge.curved=0.4, margin=c(0,0,0,0), edge.arrow.mode=0, vertex.size=10, edge.arrow.size=0, arrow.width=0, edge.width=(E(TFs_regulon_network)$weight)**2, vertex.color=TFs_cluster, vertex.label.color='black', vertex.label.cex=1, vertex.label.family="Arial")

set.seed(154)
plot.igraph(TFs_regulon_network, layout=layout_with_fr(TFs_regulon_network, niter=2000), edge.curved=0.4,  margin=c(0,0,0,0), edge.arrow.mode=0, vertex.size=10, edge.arrow.size=0, arrow.width=0, edge.width=(E(TFs_regulon_network)$weight)**2*2, vertex.color=TFs_cluster, vertex.label.color='black', vertex.label.cex=0.8, vertex.label.family="Arial")

```

```{r}
temp_func2 <- function(x){
  # return seurat cluster
  temp_df <- topTFs %>% filter(str_detect(Regulon, paste0("^",x)))
  if(nrow(temp_df) == 0){
    return("NA")
  }else{
    temp_df %<>% filter(RelativeActivity == max(RelativeActivity))
  return(temp_df$seuratCluster[[1]] %>% as.character())}}


set.seed(154)
df6 <- data.frame(layout_with_fr(TFs_regulon_network, niter=2000))
colnames(df6) <- c("x", "y")
df6$cluster <- factor(sapply(names(regulons_asGeneSet), temp_func2), levels = c(ctrl_filtered$celltype %>% levels(), "NA"))

ggplot(df6) + geom_point(aes(x=x, y=y, color=cluster), size=4) + scale_color_manual(values = c(colors_list[1:9], "lightgrey"), drop=FALSE) + theme_void() + theme(panel.grid = element_blank()) + stat_ellipse(aes(x=x, y=y,fill=cluster), data = df6 %>%  filter(),type="norm",geom="polygon",alpha=0.2,color=NA, level=0.9) + scale_fill_manual(values = c(colors_list[1:9], "lightgrey"), drop=FALSE) + coord_fixed(ratio=0.8)
```

```{r}

```
